import Link from 'next/link'
import styles from '@/styles/policy/index.module.css'

const TermsOfUsePage = () => (
    <main>
        <section>
            <div className={`container ${styles.privacy_container}`}>
                <h1>Books4Kids Terms of Use</h1>
        
                <div className={styles.privacy_content}>
                    <p>Books4Kids, Inc. welcome you to Books4Kids.com.  By clicking or tapping “Sign In”, “Create Account”, “Place Order” or entering or otherwise using our website, 
                        <Link className={styles.privacy_page_link} href='/'> www.Books4Kids.com </Link>
            
                    or our blog, (collectively the "Site"), you agree to and accept these terms and conditions that govern your use of the Site (the “Terms of Use” or “Terms”).
                    </p> 
            
                    <p>BY ACCESSING AND/OR USING THE SITE, YOU REPRESENT AND WARRANT THAT YOU HAVE THE RIGHT, AUTHORITY, AND CAPACITY TO ENTER INTO THE TERMS AND TO ABIDE BY ALL OF THE REQUIREMENTS SET FORTH HEREIN. YOU MAY NOT ACCESS OR USE THIS SITE OR ACCEPT THESE TERMS OF USE UNLESS YOU ARE AT LEAST 18 YEARS OLD.
                    </p>
            
                    <h2>Privacy Policy</h2>
            
                    <p>Please review our <Link className={styles.privacy_page_link} href='/privacy_policy'>Privacy Policy </Link>, which also governs your use of our Site and is incorporated in these Terms, to understand our practices.</p>
            
                    <h2>Electronic Communications</h2>
            
                    <p>When you use our Site, or send e-mails, text messages, chat, use video calling and other communications from your desktop or mobile device to us, you are communicating with us electronically. You consent to receive communications from us electronically, such as e-mails, texts, mobile push notices, or notices and messages on this Site, and you can retain copies of these communications for your records. You agree that all agreements, notices, disclosures, and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing. Where required by applicable law, we will seek express prior written consent for marketing text messages or calls to you.
                    </p>
            
                    <h2>Accounts</h2>
            
                    <p>In order to use certain features of the Site and make purchases or use other services on the Site, you may register for an account with Books4Kids ("Books4Kids Account") or you may proceed with your purchase using our guest checkout. You represent and warrant that: (a) all information you submit is truthful and accurate; (b) you will maintain the accuracy of such information and update it as necessary; and (c) your use of the Site does not violate any applicable law or regulation or these Terms.</p>
            
                    <p>You represent and warrant that you have the right to use any credit card or other means of payment that you provide to us in the Books4Kids Account, guest checkout or otherwise. If there is a problem charging your selected payment method in your Books4Kids Account, we may charge any other valid payment method associated with your Books4Kids Account.</p>
            
                    <p>You agree not to purchase any goods or services or register a Books4Kids Account using a false identity or information or on behalf of someone other than yourself.  </p>
            
                    <p>  You are responsible for maintaining the confidentiality of your Books4Kids Account login information. You are fully responsible for all activities that are associated with your Books4Kids Account (including but not limited to any purchases, posting reviews or other use of the Site). You agree to keep your username and password information confidential and not share it with anyone. You agree to immediately notify Books4Kids of any unauthorized use or suspected unauthorized use of your Books4Kids Account or any other actual or potential breach of security.</p>
            
                    <h2>Promotions</h2>
            
                    <p>
                        From time to time we may offer promotions, including discounts, special pricing, free or reduced price shipping, or other incentives. If a promotional code is required to take advantage of a promotion, such codes are limited in nature and may expire or be discontinued with or without notice. Promotional codes are void where prohibited by law. Promotional codes may not be copied, sold, or otherwise transferred. They are not redeemable for cash and are subject to cancellation or change at any time for any reason without notice. We reserve the right in our discretion to impose conditions on the offering of any promotional code. Books4Kids further reserves the right, in its sole discretion, to determine your eligibility for a promotion and prevent you from taking advantage of such promotion.
                        
                        For new Books4Kids Account promotions, unless we expressly communicate otherwise, such promotions are available only to new users that have never had a Books4Kids Account before. It is a violation of these Terms of Use to sign up for a Books4Kids Account and seek such promotion if you created a Books4Kids Account in the past.  Where Books4Kids in its sole discretion determines that you are not eligible for a new Books4Kids Account promotion, we may charge you the full price.
                        
                        Products purchased from Books4Kids on the Site are intended for use in the United States of America.  We reserve the right, in our sole discretion, to cancel your order if we think you are selling any Products purchased from our Site outside the United States.
                        
                    </p>
            
                    <h2>Product Descriptions</h2>
            
                    <p>
                        Books4Kids attempts to be as accurate as possible. However, Books4Kids does not warrant that Product descriptions, depictions, colors, dimensions, ingredient lists or other content on the Site are accurate, complete, reliable, current or error-free. If a Product offered by Books4Kids is not as described, your sole remedy is to return the Product. Send an email to <Link className={styles.privacy_page_link} href='mailto:rusbooksforkids@gmail.com'> rusbooksforkids@gmail.com </Link>
                        
                        for return information.
                    </p>
            
                    <h2>Order Acceptance</h2>
            
                    <p>The receipt of an order number or an email order confirmation does not constitute the acceptance of an order or confirmation of an agreement to sell. No sale is complete until shipment. Books4Kids reserves the right, without prior notification, to limit the order quantity on any item and/or to refuse service to any customer. Verification of information may be required prior to the acceptance of an order. Prices and availability of Products are subject to change without notice. Errors will be corrected when discovered and Books4Kids reserves the right to revoke any stated offer or promotion and to correct any error, inaccuracy, or omission (including after an order has been submitted). Certain orders constitute improper use of the Site. Books4Kids reserves the right, at its sole discretion, to refuse or cancel any order for any reason. Your Books4Kids Account may also be restricted or terminated for any reason, at Books4Kids's sole discretion.</p>
            
                    <h2>Risk of Loss and Shipping and Delivery</h2>
            
                    <p>All items purchased from Books4Kids are made pursuant to a shipment contract with a shipping carrier. This means that the risk of loss and title for such items pass to you upon delivery of the Products to the carrier. Products will be shipped to the address designated by you, if applicable, so long as such address is complete and complies with any shipping restrictions contained on the Site. The time and location of delivery of the Products to you is at the discretion of the carrier.  The carrier will attempt to deliver the Products to your door but in the case your front door is not easily accessible, the carrier will attempt to deliver your Products at an alternative location at your premises at carrier’s sole discretion.</p>
            
                    <h2>Permissible Uses of the Site</h2>
            
                    <p>Subject to these Terms of Use, Books4Kids grants you a limited, non-transferable, non-exclusive, license to access and make personal use of the Site. This license does not include the right to access or use the Site for any of the restricted purposes set forth below. Books4Kids may terminate this license at any time for any reason.</p>
            
                    <p>The rights granted to you are subject to the following restrictions: (a) you shall not use the Site to place an order for resale on behalf of yourself or a third party for resale by that or another third party—we reserve the right, in our sole discretion, to cancel bulk purchases or purchases that, in our judgment, appear to be placed by dealers, resellers, drop shippers, or distributors; (b) you shall not license, sublicense, reproduce, sell, rent, lease, transfer, assign, distribute, host, or otherwise commercially exploit the Site, its Products or its content without the express written consent of Books4Kids; (c) you shall not modify, make derivative works of, disassemble, reverse compile or reverse engineer any part of the Site; (d) you shall not access the Site in order to build a similar or competitive service, or to download, copy or collect content or account information for the benefit of another third party, including for purposes of resale of any of the Products; (e) except as expressly stated herein, no part of the Site may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted in any form or by any means without Books4Kids's express written consent;  (f) you shall not frame or utilize framing techniques to enclose any trademark, logo, or other proprietary information or content (including images and text descriptions) of the Site without Books4Kids's express written consent; and (g) you may only use the Site as permitted by law.</p>
            
                    <p>Books4Kids reserves the right, at any time, to modify, suspend, or discontinue the Site or any part thereof with or without notice. You agree that Books4Kids will not be liable to you or to any third party for any modification, suspension, or discontinuance of the Site or any part thereof.  Any rights not expressly granted to you in these Term of Use are reserved and retained by Books4Kids, its licensors, suppliers, or other content providers.</p>
            
                    <p>UNAUTHORIZED COPYING, REPRODUCTION, MODIFYING, REPUBLISHING, UPLOADING, DOWNLOADING, POSTING, TRANSMITTING, MAKING DERIVATIVE WORKS OF OR DUPLICATING ALL OR ANY PART OF THE SITE IS PROHIBITED.</p>
            
                    <h2>User Content</h2>
            
                    <p>"User Content" of the Site means any and all information and content, including photographs, that such user submits to Books4Kids by any means, including through social media (e.g., Facebook, YouTube, Instagram, Pinterest, Twitter, LinkedIn), uses with the Site (e.g., a user profile, product review, question & answer), or when you otherwise interact with Books4Kids (e.g., when you send us emails). You are solely responsible for your User Content. You assume all risks associated with use of your User Content, including any reliance on its accuracy, completeness or usefulness by others, or any disclosure of your User Content that makes you or any third party personally identifiable. You hereby affirm, represent, and warrant that (a) you own, or have the necessary licenses, rights, and/or consents to use your User Content with the Site as described herein and (b) your User Content does not violate the Acceptable Use policy in these Terms. You may not state or imply that your User Content is in any way provided, sponsored, or endorsed by Books4Kids. Because you alone are responsible for your User Content (and not Books4Kids), you may expose yourself to liability if, for example, your User Content violates the Acceptable Use policy. Books4Kids is not obligated to backup any User Content, makes no representation that it will do so, and you agree that Books4Kids may delete User Content at any time.</p>
            
                    <p>By submitting your User Content or using it with the Site, you automatically grant, and you represent and warrant that you have the right to grant, to Books4Kids an irrevocable, nonexclusive, royalty-free and fully paid worldwide license to reproduce, distribute, publicly display and perform, prepare derivative works of, incorporate into other works, and otherwise use your User Content, and to grant sublicenses of the foregoing, solely for the purposes of including your User Content in the Site, Books4Kids social media platforms,  marketing or promotional initiatives or any other business purpose. You agree to irrevocably waive (and cause to be waived) any claims and assertions of publicity or moral rights, or attribution with respect to your User Content.</p>
            
                    <p>Books4Kids will treat any feedback, communications, or suggestions you provide to Books4Kids as non-confidential and non-proprietary subject to the limits of applicable law and our Privacy Policy. Thus, in the absence of a written agreement with Books4Kids to the contrary, you agree that you will not submit to Books4Kids any information or ideas that you consider to be confidential or proprietary.</p>
            
                    <p>Because we do not control User Content, you acknowledge and agree that we are not responsible for any User Content and we make no guarantees regarding the accuracy, currency, suitability, or quality of any User Content, and we assume no responsibility for any User Content or your interactions with other Site users. You agree that Books4Kids will not be responsible for any loss or damage incurred as the result of any such interactions. If there is a dispute between you and any Site user, we are under no obligation to become involved.</p>
            
                    <h2>Acceptable Use Policy</h2>
            
                    <p>In connection with your use of the Site and interactions with Books4Kids and its employees and users, you agree not to collect, upload, transmit, display, communicate by email, telephone or electronically, or distribute any User Content (a) that violates any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy rights, right of publicity, or any other intellectual property or proprietary right; (b) that is unlawful, harassing, abusive, tortious, threatening, harmful, abusive, invasive of another's privacy, vulgar, defamatory, false, intentionally misleading, trade libelous, pornographic, obscene, patently offensive (e.g., material that promotes racism, bigotry, hatred, or physical harm of any kind against any group or individual) or otherwise objectionable material of any kind or nature or which is harmful to minors in any way; or (c) in violation of any law, regulation, or obligations or restrictions imposed by any third party.</p>
            
                    <p>In addition, you agree not to use the Site to: (a) upload, transmit, or distribute any computer viruses, worms, or any software intended to damage or alter a computer system or data; (b) send unsolicited or unauthorized advertising, promotional materials, junk mail, spam, chain letters, pyramid schemes, or any other form of duplicative or unsolicited messages, whether commercial or otherwise; (c) harvest, collect, gather or assemble information or data regarding other users, including e-mail addresses, without their consent; (d) interfere with or disrupt servers or networks connected to the Site or violate the regulations, policies or procedures of such networks; (e) attempt to gain unauthorized access to the Site, other computer systems or networks connected to or used together with the Site, through password mining or other means; (f) harass or interfere with another user's use and enjoyment of the Site; (g) purchase Products for resale.</p>
            
                    <p>We reserve the right (but have no obligation under these Terms of Use) at our sole discretion to review any User Content, investigate, and/or take appropriate action against you if you violate the Acceptable Use Policy or any other provision of these Terms, including removing or modifying your User Content, terminating your Books4Kids Account, and/or reporting you to law enforcement authorities. We may also remove or modify your User Content if it, in our sole judgment, violates the rights of, harms, or threatens the safety of any other person, or creates liability for us or any other person. In order to cooperate with legitimate governmental requests, subpoenas or court orders, or to protect our business and members, we may access and disclose any information we consider necessary or appropriate, including your Books4Kids Account username and password, Internet Protocol (IP) address and traffic information, usage history, and your User Content.</p>
            
                    <h2>Third Party Sites and Other Users</h2>
            
                    <p>The Site may contain links to, or advertisements for, third party web sites and products (collectively, "Third Party Sites") (for example, social media sites such as Facebook, YouTube, Twitter, or Pinterest). Such Third Party Sites are not under the control of Books4Kids and Books4Kids is not responsible for any Third Party Sites. Books4Kids provides links to these Third Party Sites only as a convenience and does not review, approve, monitor, endorse, warrant, or make any representations with respect to Third Party Sites. You agree that you use all Third Party Sites at your own risk. When you link to a Third Party Site, the applicable service provider's terms and policies, including privacy and data gathering practices govern. You should make whatever investigation you feel necessary or appropriate before proceeding with any transaction with any Third Party Site.</p>
            
                    <p>You hereby release us, our officers, employees, directors, agents, affiliates, subsidiaries, parents, joint ventures, successors and any other companies under common control with us from claims, demands any and all losses, damages, rights, claims, and actions of any kind including personal injuries, death, and property damage, that are either directly or indirectly related to or arise out of any interactions with or conduct of other Site users or Third Party Sites.</p>
            
                    <h2>Disclaimer of Warranties</h2>
            
                    <p>Books4Kids intends for the information and data contained in the Site to be accurate and reliable but since the information and data have been compiled from a variety of sources, they are provided 'AS IS' and "AS AVAILABLE". You expressly agree that your use of the Site and any information contained therein is at your sole risk. NEITHER Books4Kids NOR ITS THIRD PARTY SERVICE PROVIDERS, CONTRACTORS, PARTNERS, SUPPLIERS OR AFFILIATES WARRANT THE ACCURACY OR COMPLETENESS OF THE CONTENT PROVIDED ON THIS SITE OR THE PRODUCTS OR SERVICES OFFERED FOR SALE ON THIS SITE. WE CANNOT AND DO NOT WARRANT THAT YOUR USE OF THIS SITE WILL BE UNINTERRUPTED, SECURE OR ERROR FREE. ACCORDINGLY, TO THE EXTENT PERMITTED BY APPLICABLE LAW, Books4Kids EXPRESSLY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, ACCURACY, MERCHANTABILITY AND FITNESS FOR A PURPOSE, AND ANY WARRANTIES THAT MAY ARISE FROM COURSE OF DEALING, COURSE OF PERFORMANCE OR USAGE OF TRADE. Some jurisdictions do not allow the disclaimer of warranties so such disclaimers may not apply to you.</p>
            
                    <h2>Limitation on Liability</h2>
            
                    <p>IN NO EVENT SHALL Books4Kids, OUR OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AFFILIATES, SUBSIDIARIES, PARENTS, JOINT VENTURES, SUCCESSORS AND ANY OTHER COMPANIES UNDER COMMON CONTROL WITH US, ANY INDEPENDENT CONTRACTORS, OR THIRD PARTY VETERINARIANS (“Books4Kids GROUP”), BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY LOST PROFIT OR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL OR PUNITIVE DAMAGES ARISING FROM OR IN ANY WAY RELATED TO YOUR RELATIONSHIP WITH Books4Kids GROUP, YOUR USE OF THE SITE, PRODUCTS, TOOLS, APPLICATIONS, OR THIRD PARTY SITES, OR YOUR INTERACTION WITH OR RELIANCE ON ANY UPDATES OR ADVICE FROM Books4Kids OR ANY SUCH PERSON OR ENTITY EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. ACCESS TO, AND USE OF, THE SITE, PRODUCTS, TOOLS, APPLICATIONS AND THIRD PARTY SITES AND ANY INTERACTIONS WITH OR RELIANCE ON UPDATES OR ADVICE FROM Books4Kids OR ANY SUCH PERSON OR ENTITY ARE AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE IN CONNECTION THEREWITH INCLUDING BUT NOT LIMITED TO YOUR COMPUTER SYSTEM OR LOSS OF DATA RESULTING THEREFROM. NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, OUR LIABILITY TO YOU FOR ANY DAMAGES ARISING FROM OR IN ANY WAY RELATED TO YOUR RELATIONSHIP WITH Books4Kids GROUP, ANY INTERACTIONS WITH OR RELIANCE ON ADVICE FROM ANY SUCH PERSON OR ENTITY, OR THESE TERMS (FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION), WILL AT ALL TIMES BE LIMITED TO THE GREATER OF (A) FIFTY US DOLLARS ($50) OR (B) AMOUNTS YOU'VE PAID Books4Kids IN THE PRIOR 12 MONTHS. YOU AGREE THAT ANY CLAIM BETWEEN US MUST BE BROUGHT WITHIN TWO (2) YEARS OF THE EVENT(S) GIVING RISE TO SUCH CLAIM OR THE DATE OF THE RELEVANT PURCHASE, WHICHEVER IS EARLIER.</p>
            
                    <p>SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OF CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU AND YOU MAY ALSO HAVE OTHER LEGAL RIGHTS THAT VARY FROM JURISDICTION TO JURISDICTION.</p>
            
                    <h2>Indemnity</h2>
            
                    <p>You agree to indemnify and hold Books4Kids Group harmless from any claim or demand, including for any related costs and attorneys' fees, made by any third party due to or arising out of (a) your use of the Site or Products, (b) your User Content, (c) your violation of these Terms, or (d) your interaction with such independent contractors or reliance on any advice provided by them. Books4Kids Group reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us and you agree to cooperate with our defense of these claims. You agree not to settle any matter without the prior written consent of Books4Kids. Books4Kids will use reasonable efforts to notify you of any such claim, action or proceeding upon becoming aware of it.</p>
            
                    <h2>Dispute Resolution and Agreement to Individual Arbitration</h2>
            
                    <p>EXCEPT FOR A CLAIM THAT MAY BE BROUGHT IN SMALL CLAIMS COURT, YOU AND Books4Kids AGREE TO GIVE UP ANY RIGHTS TO LITIGATE CLAIMS IN A COURT OR BEFORE A JURY OR TO PARTICIPATE IN A CLASS ACTION OR REPRESENTATIVE ACTION WITH RESPECT TO A CLAIM. OTHER RIGHTS THAT YOU WOULD HAVE IF YOU WENT TO COURT, SUCH AS ACCESS TO DISCOVERY, ALSO MAY BE UNAVAILABLE OR LIMITED IN ARBITRATION.</p>
            
                    <p>Covered Disputes and Arbitration Requirement.  Any and all disputes between you and Books4Kids, including disputes arising from or relating to the Site, these Terms of Use, the Privacy Policy, and Conditions and any other terms and conditions that may apply to our Site and/or Products, programs and services and their interpretation or the breach, termination or validity thereof, any purchase on the Site, communications between you and Books4Kids, the reliance on any advice provided by independent contractors or third party veterinarians in connection with the Site, or any Products or promotions provided by Books4Kids, including disputes about the validity, scope or enforceability of this arbitration provision (collectively, "Covered Disputes") will be resolved by binding arbitration administered by the American Arbitration Association (“AAA”) under the AAA's Consumer Arbitration Rules in effect on the date the claim was filed, available at www.adr.org or by calling the AAA at 800-778-7879.  This arbitration agreement applies to any and all disputes occurring before or after this agreement and supersedes our previous arbitration agreements.  The arbitrator will have the power to grant whatever relief would be available in court under law or in equity, including public injunctive relief, and any award of the arbitrator(s) will be final and binding on each of the parties and may be entered as a judgment in any court of competent jurisdiction. Notwithstanding the above, you or Books4Kids can bring any individual claim in small claims court consistent with the jurisdictional limitations of such court.</p>
            
                    <p>Governing Law.  For purposes of this section, these Terms of Use and related transactions will be subject to and governed by the Federal Arbitration Act, 9 U.S.C. sec. 1-16 (“FAA”). To the extent state law applies to any portion of a proceeding brought by you or us, the applicable law will be the law of the state of your residence, as determined based on your shipping address on file with Books4Kids.</p>
            
                    <p>Fees and Costs.   Except for a demand determined by an arbitrator or court to be frivolous, brought in bad faith, or where the initiating party has failed to follow the pre-arbitration dispute resolution process below, Books4Kids will pay the filing fees for both parties. The AAA consumer rules will otherwise apply to determine the costs and expenses due from each party.</p>
            
                    <p>Batch Arbitration. To increase the efficiency of administration and resolution of arbitrations, in the event 100 or more similar individual arbitration demands presented by or with the assistance or coordination of the same law firm or organization are submitted to AAA or another arbitration provider (if AAA is unavailable) against Books4Kids within a 90-day period (or in otherwise close proximity), the arbitration provider shall (i) administer the arbitration demands in batches of 100 demands per batch (to the extent there are fewer than 100 arbitration demands left over after the batching described above, a final batch will consist of the remaining demands); (ii) designate one arbitrator for each batch; and (iii) provide for a single filing fee due per side per batch. You agree to cooperate in good faith with Books4Kids and AAA to implement such a “batch approach” or other similar approach to provide for an efficient resolution of claims, including the payment of single filing and administrative fees for batches of claims. This “Batch Arbitration” provision shall in no way be interpreted as authorizing class arbitration of any kind. </p>
            
                    <p>Location.  At your election, the arbitration will take place in the county in which you reside or, if you choose, by telephone, video conference, or based on the parties’ written submissions.</p>
            
                    <p>Required Pre-Arbitration Dispute Resolution.  Prior to initiating any arbitration, the initiating party will give the other party at least 60-days' advanced written notice, along with any supporting documents and information, of its intent to file for arbitration. Books4Kids will provide such notice by e-mail to your e-mail address on file with Books4Kids and you must provide such notice by e-mail to legal@Books4Kids.com. During such 60-day notice period, the parties will endeavor to settle amicably by mutual discussions any Covered Disputes. Failing such amicable settlement and expiration of the notice period, either party may initiate arbitration. This provision is a precondition to any arbitration demand, and any party making an arbitration demand must certify that it has complied with the requirement when filing an arbitration demand and AAA may not accept any demand without this certification.</p>
            
                    <p>CLASS ACTION WAIVER.  Books4Kids AND YOU AGREE THAT ANY COVERED DISPUTE HEREUNDER WILL BE SUBMITTED TO ARBITRATION ON AN INDIVIDUAL BASIS ONLY (EXCEPT AS SET FORTH IN THE “BATCH ARBITRATION” PROVISION DESCRIBED ABOVE). NEITHER Books4Kids NOR YOU ARE ENTITLED TO ARBITRATE ANY COVERED DISPUTE AS A CLASS, REPRESENTATIVE OR PRIVATE ATTORNEY ACTION AND THE ARBITRATOR(S) WILL HAVE NO AUTHORITY TO PROCEED ON A CLASS, REPRESENTATIVE OR PRIVATE ATTORNEY GENERAL BASIS (EXCEPT AS SET FORTH IN THE “BATCH ARBITRATION” PROVISION DESCRIBED ABOVE). If any provision of the agreement to arbitrate in this section is found unenforceable, the unenforceable provision will be severed and the remaining arbitration terms will be enforced (but in no case will there be a class, representative or private attorney general arbitration).</p>
            
                    <p>
                        Miscellaneous.  Notwithstanding any provision in these Terms to the contrary, we agree that if Books4Kids makes any future material change to this dispute resolution provision, it will not apply to any individual claim(s) for which you had already provided notice to Books4Kids. In the event that this arbitration agreement does not apply to a given dispute, then the parties agree to the exclusive jurisdiction of the state and federal courts in Broward County, Florida to resolve such claims.
                    </p>
            
                    <h2>Term and Termination</h2>
            
                    <p>Subject to this Section, these Terms of Use will remain in full force and effect while you use the Site. We may (a) suspend your rights to use the Site (as well as your Books4Kids Account) or (b) terminate your Books4Kids Account, at any time for any reason at our sole discretion, including for any use of the Site in violation of the Terms or if we believe you are younger than 18. Upon termination of these Terms, your Books4Kids Account and right to access and use the Site will terminate immediately. You understand that any termination of your Books4Kids Account may involve deletion of any User Content you may have posted. Books4Kids will not have any liability whatsoever to you for any termination of these Terms, including for termination of your Books4Kids Account or deletion of your User Content.</p>
            
                    <p>The provisions herein related to our IP rights, User Content, acceptable use, disclaimer of warranties, indemnity, limitation and liability, and dispute resolution, including individual arbitration, together with any other rights and obligations which by their nature should survive, will survive such termination, including the end of any other aspect of the relationship between you and Books4Kids, including your decision to stop purchasing from Books4Kids or the cancellation, opt-out, or end of any participation in any service, program, or promotion offered by Books4Kids.</p>
            
                    <h2>General</h2>
            
                    <p>We reserve the right to make changes to our Site at any time, including but not limited to our Terms, our Privacy Policy, and any other terms and conditions that may apply to our Site and/or Products, programs and services. Each time you use our Site, you should visit and review the then current terms and policies that apply to your transactions and use of our Site. If you do not agree to be bound by the then current terms and policies, your sole remedy is not to use our Site. If any provision of these Terms are deemed invalid, void, or for any reason unenforceable, any such term shall be deemed severable and shall not affect the validity and enforceability of any other terms.</p>
            
                    <p>Our failure to exercise or enforce any right or provision of these Terms of Use shall not operate as a waiver of such right or provision. The section titles in these Terms are for convenience only and have no legal or contractual effect. The word "including" means including without limitation. If any provision of these Terms are, for any reason, held to be invalid or unenforceable, the other provisions of these Terms will be unimpaired and the invalid or unenforceable provision will be deemed modified so that it is valid and enforceable to the maximum extent permitted by law. The Terms of Use, and your rights and obligations herein, may not be assigned, subcontracted, delegated, or otherwise transferred by you without Books4Kids's prior written consent, and any attempted assignment, subcontract, delegation, or transfer in violation of the foregoing will be null and void. The Terms shall be binding upon assignees.</p>
            
                    <h2>Contact Information</h2>
            
                    <p>For questions or concerns about these Terms, including your legal relationship with Books4Kids, please contact us at:</p>
            
                        <p>Books4Kids</p>
            
                        <p>3438 Nekoosa Street</p>
            
                        <p>North Port, Florida 23487</p>
            
                        <Link className={styles.privacy_page_link} href='mailto:rusbooksforkids@gmail.com'> rusbooksforkids@gmail.com </Link>
                </div>
            </div>
        </section>

    </main>
)

export default TermsOfUsePage;
